### ISSUE TITLE
Getting error that build.ts file does not exist

### ISSUE THREAD

**Issue by PeziBuuu** [4dams/angular-build-info#1]
Hey, I just installed your plugin and run 'angular-build-info --init' and then i get following error:
An error occured writing to `D:\Programme\Development\PMI\pmi-client/src/build.ts`, does the path exist?

The file exist. I also tried to remove it and run the command, but still the same. Even if i create the file and run the command 'angular-build-info', I get the same error. Seems the system can'
t or won't find the file.

![Unbenannt2](https://user-images.githubusercontent.com/57503624/71821357-36256400-3092-11ea-8199-5bc36704e8ae.PNG)

![error](https://user-images.githubusercontent.com/57503624/71821293-09714c80-3092-11ea-8667-56fdc6ec3eff.PNG)

![Unbenannt3](https://user-images.githubusercontent.com/57503624/71821462-813f7700-3092-11ea-8f88-196b73837702.PNG)

Hope you can help me.

**Comment by juriadams** [comment]
Hey there, @PeziBuuu! I have moved the issue to our new Repository: https://github.com/inexio/angular-build-info/issues/1 

I will look into this issue soon, thanks for reporting!

### **I will close the issue here as it will be continued in the [new Repository](https://github.com/inexio/angular-build-info/issues/1 )!**

**Comment by PeziBuuu** [comment]
Hey,

Thanks for the fast reply. I was just going to write you the same. It has to do with the windows path of the angular app. Windows add the backsplash and while you have the Forwardslash in your code and then the system can't find the file, because the path is obviously wrong. Hope this will help you.
